Fixed issue with ambigous reference preventing dart2js
It appears the langspec changed causing the following:
Error: Variable 'subscription' is referenced during its initialization.